package tig.grpc.client;

/* these are generated by the hello-world-server contract */
import io.grpc.StatusRuntimeException;
import tig.grpc.contract.Tig;
import tig.grpc.contract.TigServiceGrpc;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

public class Client {

	public static void main(String[] args) throws Exception {

		// check arguments
		if (args.length < 2) {
			System.err.println("Argument(s) missing!");
			System.err.printf("Usage: java %s host port%n", Client.class.getName());
			return;
		}

		final String host = args[0];
		final int port = Integer.parseInt(args[1]);
		final String target = host + ":" + port;

		final ManagedChannel channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();

		TigServiceGrpc.TigServiceBlockingStub stub = TigServiceGrpc.newBlockingStub(channel);

		try {
			System.out.println(stub.register(Tig.LoginRequest.newBuilder().setUsername("carolzocas2").setPassword("1234").build()).getCode().toString());
		} catch(StatusRuntimeException e) {
			System.out.println(e.getStatus().getCode());
			System.out.println(e.getStatus().getDescription());
		}
		// A Channel should be shutdown before stopping the process.
		channel.shutdownNow();
	}

}
