package tig.grpc.server.api;

/* these are generated by the hello-world-server contract */
import sirs.grpc.contract.api.HelloWorld;
import sirs.grpc.contract.api.HelloWorldServiceGrpc;

import io.grpc.stub.StreamObserver;

public class DocumentServiceImpl extends HelloWorldServiceGrpc.HelloWorldServiceImplBase {

	@Override
	public void greeting(HelloWorld.HelloRequest request, StreamObserver<HelloWorld.HelloResponse> responseObserver) {

		// HelloRequest has auto-generated toString method that shows its contents
		System.out.println(request);

		// You must use a builder to construct a new Protobuffer object
		HelloWorld.HelloResponse response = HelloWorld.HelloResponse.newBuilder()
				.setGreeting("Hello " + request.getName()).build();

		// Use responseObserver to send a single response back
		responseObserver.onNext(response);

		// When you are done, you must call onCompleted
		responseObserver.onCompleted();
	}

}
